# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=250, null=True)),
                ('campus', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
